# Задание 1

#### 1. Импортируйте библиотеку Numpy и дайте ей псевдоним np.

In [206]:
import numpy as np

 * Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [244]:
a = np.arange(12,24)

 * Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [208]:
a.reshape(3,4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [209]:
a.reshape(4,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [210]:
a.reshape(2,6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [211]:
a.reshape(6,2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [212]:
a.reshape(12,1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

 * Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [245]:
a.reshape(3,-1)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [209]:
a.reshape(4,-1)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [246]:
a.reshape(-1,6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [247]:
a.reshape(-1,2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [248]:
a.reshape(-1,1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

* Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [213]:
# судя по тому что ndim = 2 то по идее ответ НЕТ нельзя назвать одномерным
a.reshape(12,1).ndim

2

#### 2. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0.

In [266]:
a = np.random.normal(size=(3,4))
a

array([[ 0.57089051,  1.13556564,  0.95400176,  0.65139125],
       [-0.31526924,  0.75896922, -0.77282521, -0.23681861],
       [-0.48536355,  0.08187414,  2.31465857, -1.86726519]])

 * Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [215]:
b = a.flatten()
b

array([ 1.57921282,  0.76743473, -0.46947439,  0.54256004, -0.46341769,
       -0.46572975,  0.24196227, -1.91328024, -1.72491783, -0.56228753,
       -1.01283112,  0.31424733])

#### 3. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [280]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

 * Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2.

In [277]:
b = np.arange(20, 1, -2).reshape(1,10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

 * В чем разница между массивами a и b?

**если я правильно понял задачу то во для "b" необходимо было создать по сути матрицу просто из одной строки
если я правильно понял то тогда разница между а и б в том a.ndim =1 а b.ndim = 2 т.е. в размерности**

**если я неправильно понял и тут был просто вопрос будет ли разницам при создании массива от 20 до 0 или 20 до 1 с интервалом 2 - то разницы не будет**

#### 4. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [218]:
a = np.zeros((2,2))
b = np.ones((3,2))
v = np.vstack((a,b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [219]:
v.size

10

#### 5. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.

In [220]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

* Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов.

In [221]:
A = a.reshape((4,3))
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

* Получить матрицу At путем транспонирования матрицы A.

In [222]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

* Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.

In [223]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

* Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [224]:
B.size

16

In [225]:
#  вычислить не получиться потому что полученная матрица является вырожденной - определитель = 0
np.linalg.det(B) == 0

True

#### 6. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [226]:
np.random.seed(42)

* Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [227]:
c = np.random.randint(0, 16, (16,))
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

* Поменяйте его форму так, чтобы получилась квадратная матрица C.

In [228]:
C = c.reshape((4,4))
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

* Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.

In [229]:
D = B + 10 * C
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

* Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [230]:
np.linalg.det(D)

-28511999.999999944

In [231]:
np.linalg.matrix_rank(D)

4

In [272]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

#### 7. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы.

In [275]:
# D_inv = np.where(D_inv < 0, 0, 1)
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

* С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4. Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [234]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [235]:
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [276]:
E = np.where(D_inv, B, C)
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])

# Задание 2

* Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7.
* Будем считать, что каждый столбец - это признак, а строка - наблюдение.

In [237]:
a = np.array([[1,2,3,3,1], [6,8,11,10,7]]).T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

* Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [238]:
mean_a = np.mean(a, axis=0)
mean_a

array([2. , 8.4])

# Задание 3

* Вычислите массив  a_centered, отняв от значений массива  а средние значения соответствующих признаков, содержащиеся в массиве  mean_a. 
* Вычисление должно производиться в одно действие.
* Получившийся массив должен иметь размер 5x2.

In [239]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

# Задание 4

* Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp.
* Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [240]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])
a_centered_sp

8.0

In [241]:
N = a_centered.shape[0]
a_centered_sp / (N-1)

2.0

# Задание 5
* Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве а. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.
* В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov.
* В качестве аргумента m функция np.cov должна принимать транспонированный массив a. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.
* Подробнее узнать о ковариации можно здесь: https://studopedia.ru/9_153900_viborochnaya-kovariatsiya-i-viborochnaya-dispersiya.html

In [242]:
cv = np.cov(a.transpose())
cv[0,1]

2.0